hs_chapters = {
    '01': 'Live Animals',
    '02': 'Meat',
    '03': 'Fish',
    '04': 'Dairy, Eggs, Honey',
    '05': 'Other Animal Products',
    '06': 'Live Trees and Plants',
    '07': 'Edible Vegetables',
    '08': 'Edible Fruit and Nuts',
    '09': 'Coffee, Tea, Spices',
    '10': 'Cereals',
    '11': 'Milling Products, Malt, Starch',
    '12': 'Oil Seeds, Grains, Plants',
    '13': 'Lac, Gums, Resins, Extracts',
    '14': 'Vegetable Plaiting Materials',
    '15': 'Animal/Vegetable Fats and Oils',
    '16': 'Preparations of Meat and Fish',
    '17': 'Sugars and Confectionery',
    '18': 'Cocoa and Preparations',
    '19': 'Cereal, Flour, Milk Preparations',
    '20': 'Vegetable, Fruit and Nut Preparations',
    '21': 'Miscellaneous Edible Preparations',
    '22': 'Beverages, Spirits, Vinegar',
    '23': 'Food Industry Residues, Prepared Animal Feed',
    '24': 'Tobacco',
    '25': 'Salt, Sulphur, Stone, Cement',
    '26': 'Ores, Slag, Ash',
    '27': 'Mineral Fuels, Oils, Waxes',
    '28': 'Inorganic Chemicals',
    '29': 'Organic Chemicals',
    '30': 'Pharmaceutical Products',
    '31': 'Fertilizers',
    '32': 'Tanning, Dyeing, Paints, Putty',
    '33': 'Essential Oils, Cosmetics',
    '34': 'Soap, Waxes, Dental Preparations',
    '35': 'Albuminoidal Substances, Starches, Glues',
    '36': 'Explosives, Pyrotechnics',
    '37': 'Photographic/Cinematographic Goods',
    '38': 'Miscellaneous Chemical Products',
    '39': 'Plastics',
    '40': 'Rubber',
    '41': 'Raw Hides, Skins, Leather',
    '42': 'Leather Articles, Saddlery, Bags',
    '43': 'Furskins and Artificial Fur',
    '44': 'Wood and Wood Charcoal',
    '45': 'Cork',
    '46': 'Manufactures of Straw, Basketware',
    '47': 'Wood Pulp, Recovered Paper',
    '48': 'Paper and Paperboard',
    '49': 'Printed Books, Newspapers, Pictures',
    '50': 'Silk',
    '51': 'Wool, Animal Hair, Horsehair',
    '52': 'Cotton',
    '53': 'Other Vegetable Textile Fibers',
    '54': 'Man-Made Filaments',
    '55': 'Man-Made Staple Fibers',
    '56': 'Wadding, Felt, Twine, Ropes',
    '57': 'Carpets and Floor Coverings',
    '58': 'Special Woven Fabrics, Lace, Tapestries',
    '59': 'Impregnated/Coated Textile Fabrics',
    '60': 'Knitted or Crocheted Fabrics',
    '61': 'Apparel and Accessories, Knitted',
    '62': 'Apparel and Accessories, Not Knitted',
    '63': 'Other Made-Up Textiles, Sets, Worn Clothing',
    '64': 'Footwear',
    '65': 'Headgear',
    '66': 'Umbrellas, Walking Sticks',
    '67': 'Prepared Feathers, Artificial Flowers',
    '68': 'Articles of Stone, Plaster, Cement',
    '69': 'Ceramic Products',
    '70': 'Glass and Glassware',
    '71': 'Pearls, Precious Stones, Metals, Coins',
    '72': 'Iron and Steel',
    '73': 'Articles of Iron or Steel',
    '74': 'Copper',
    '75': 'Nickel',
    '76': 'Aluminum',
    '78': 'Lead',
    '79': 'Zinc',
    '80': 'Tin',
    '81': 'Other Base Metals',
    '82': 'Tools, Cutlery of Base Metal',
    '83': 'Miscellaneous Articles of Base Metal',
    '84': 'Machinery, Mechanical Appliances, Nuclear Reactors',
    '85': 'Electrical Machinery, Equipment, Recorders',
    '86': 'Railway/Tramway Locomotives, Track Fixtures',
    '87': 'Vehicles (Not Railway/Tramway)',
    '88': 'Aircraft, Spacecraft',
    '89': 'Ships, Boats, Floating Structures',
    '90': 'Optical, Photographic, Medical Instruments',
    '91': 'Clocks and Watches',
    '92': 'Musical Instruments',
    '93': 'Arms and Ammunition',
    '94': 'Furniture, Bedding, Lighting, Prefab Buildings',
    '95': 'Toys, Games, Sports Requisites',
    '96': 'Miscellaneous Manufactured Articles',
    '97': 'Works of Art, Antiques'
}